//LOGIN ACTION TYPES
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

//USERS ACTION TYPES
export const REQUEST_USERS = 'REQUEST_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const REQUEST_USERS_FAILED = 'REQUEST_USERS_FAILED';
export const REQUEST_ADD_USERS = 'REQUEST_ADD_USERS';
export const ADD_USERS_SUCCESS = 'ADD_USERS_SUCCESS';
export const REQUEST_EDIT_USERS = 'REQUEST_EDIT_USERS';
export const EDIT_USERS_SUCCESS = 'EDIT_USERS_SUCCESS';
export const REQUEST_DELETE_USERS= 'REQUEST_DELETE_USERS';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';

//USERS PROFILE TYPES
export const REQUEST_PROFILE = 'REQUEST_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const REQUEST_PROFILE_FAILED = 'REQUEST_PROFILE_FAILED';
export const REQUEST_ADD_PROFILE = 'REQUEST_ADD_PROFILE';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';
export const REQUEST_EDIT_PROFILE = 'REQUEST_EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const REQUEST_DELETE_PROFILE= 'REQUEST_DELETE_PROFILE';
export const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS';

//OBJECTIVE TYPES
export const REQUEST_OBJECTIVE = 'REQUEST_OBJECTIVE';
export const GET_OBJECTIVE_SUCCESS = 'GET_OBJECTIVE_SUCCESS';
export const REQUEST_OBJECTIVE_FAILED = 'REQUEST_OBJECTIVE_FAILED';
export const REQUEST_ADD_OBJECTIVE = 'REQUEST_ADD_OBJECTIVE';
export const ADD_OBJECTIVE_SUCCESS = 'ADD_OBJECTIVE_SUCCESS';
export const REQUEST_EDIT_OBJECTIVE = 'REQUEST_EDIT_OBJECTIVE';
export const EDIT_OBJECTIVE_SUCCESS = 'EDIT_OBJECTIVE_SUCCESS';
export const REQUEST_DELETE_OBJECTIVE= 'REQUEST_DELETE_OBJECTIVE';
export const DELETE_OBJECTIVE_SUCCESS = 'DELETE_OBJECTIVE_SUCCESS';

//USERS INTERESTS TYPES
export const REQUEST_INTEREST = 'REQUEST_INTEREST';
export const GET_INTEREST_SUCCESS = 'GET_INTEREST_SUCCESS';
export const REQUEST_INTEREST_FAILED = 'REQUEST_INTEREST_FAILED';
export const REQUEST_ADD_INTEREST = 'REQUEST_ADD_INTEREST';
export const ADD_INTEREST_SUCCESS = 'ADD_INTEREST_SUCCESS';
export const REQUEST_EDIT_INTEREST = 'REQUEST_EDIT_INTEREST';
export const EDIT_INTEREST_SUCCESS = 'EDIT_INTEREST_SUCCESS';
export const REQUEST_DELETE_INTEREST= 'REQUEST_DELETE_INTEREST';
export const DELETE_INTEREST_SUCCESS = 'DELETE_INTEREST_SUCCESS';

//USERS MEETINGS TYPES
export const REQUEST_MEETING = 'REQUEST_MEETING';
export const GET_MEETING_SUCCESS = 'GET_MEETING_SUCCESS';
export const REQUEST_MEETING_FAILED = 'REQUEST_MEETING_FAILED';
export const REQUEST_ADD_MEETING = 'REQUEST_ADD_MEETING';
export const ADD_MEETING_SUCCESS = 'ADD_MEETING_SUCCESS';
export const REQUEST_EDIT_MEETING = 'REQUEST_EDIT_MEETING';
export const EDIT_MEETING_SUCCESS = 'EDIT_MEETING_SUCCESS';
export const REQUEST_DELETE_MEETING= 'REQUEST_DELETE_MEETING';
export const DELETE_MEETING_SUCCESS = 'DELETE_MEETING_SUCCESS';

//USERS FEEDBACKS TYPES
export const REQUEST_FEEDBACKS = 'REQUEST_FEEDBACKS';
export const GET_FEEDBACKS_SUCCESS = 'GET_FEEDBACKS_SUCCESS';
export const REQUEST_FEEDBACKS_FAILED = 'REQUEST_FEEDBACKS_FAILED';
export const REQUEST_ADD_FEEDBACKS = 'REQUEST_ADD_FEEDBACKS';
export const ADD_FEEDBACKS_SUCCESS = 'ADD_FEEDBACKS_SUCCESS';
export const REQUEST_EDIT_FEEDBACKS = 'REQUEST_EDIT_FEEDBACKS';
export const EDIT_FEEDBACKS_SUCCESS = 'EDIT_FEEDBACKS_SUCCESS';
export const REQUEST_DELETE_FEEDBACKS= 'REQUEST_DELETE_FEEDBACKS';
export const DELETE_FEEDBACKS_SUCCESS = 'DELETE_FEEDBACKS_SUCCESS';

//USERS MATCH TYPES
export const REQUEST_MATCH = 'REQUEST_MATCH';
export const GET_MATCH_SUCCESS = 'GET_MATCH_SUCCESS';
export const REQUEST_MATCH_FAILED = 'REQUEST_MATCH_FAILED';
export const REQUEST_ADD_MATCH = 'REQUEST_ADD_MATCH';
export const ADD_MATCH_SUCCESS = 'ADD_MATCH_SUCCESS';
export const REQUEST_EDIT_MATCH = 'REQUEST_EDIT_MATCH';
export const EDIT_MATCH_SUCCESS = 'EDIT_MATCH_SUCCESS';
export const REQUEST_DELETE_MATCH= 'REQUEST_DELETE_MATCH';
export const DELETE_MATCH_SUCCESS = 'DELETE_MATCH_SUCCESS';